# Generated by Django 5.2.1 on 2025-05-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_public"], name="habit_habit_user_id_5f2cfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(fields=["time"], name="habit_habit_time_d5a2ea_idx"),
        ),
    ]
